ALTER TABLE media ADD COLUMN r2_key TEXT DEFAULT '';
ALTER TABLE media ADD COLUMN original_name TEXT DEFAULT '';
ALTER TABLE media ADD COLUMN kind TEXT DEFAULT 'image';
ALTER TABLE media ADD COLUMN size INTEGER DEFAULT 0;
ALTER TABLE media ADD COLUMN mime_type TEXT DEFAULT '';
ALTER TABLE media ADD COLUMN uploaded_by TEXT DEFAULT '';
