import { Router } from 'express';
import { approveSubscriptionRequest, createSubscriptionRequest, createUnlockRequest, deleteSubscriptionRequest, getSubscriptionRequests, rejectSubscriptionRequest } from '../controllers/SubscriptionController.js';
import { validateSubscription } from '../middlewares/validation.js';
import { authenticate, requireAnyRole } from '../middlewares/auth.js';
import { UserRole } from '../../types.js';
const router = Router();
router.post('/subscription-requests', validateSubscription, createSubscriptionRequest);
router.post('/unlock-requests', createUnlockRequest);
router.get('/subscription-requests', authenticate, requireAnyRole(UserRole.ADMIN, UserRole.SUPER_ADMIN), getSubscriptionRequests);
router.get('/subscribers', authenticate, requireAnyRole(UserRole.ADMIN, UserRole.SUPER_ADMIN), getSubscriptionRequests);
router.post('/subscription-requests/:id/approve', authenticate, requireAnyRole(UserRole.ADMIN, UserRole.SUPER_ADMIN), approveSubscriptionRequest);
router.post('/subscription-requests/:id/reject', authenticate, requireAnyRole(UserRole.ADMIN, UserRole.SUPER_ADMIN), rejectSubscriptionRequest);
router.delete('/subscription-requests/:id', authenticate, requireAnyRole(UserRole.ADMIN, UserRole.SUPER_ADMIN), deleteSubscriptionRequest);
router.post('/subscribers/:id/approve', authenticate, requireAnyRole(UserRole.ADMIN, UserRole.SUPER_ADMIN), approveSubscriptionRequest);
router.post('/subscribers/:id/reject', authenticate, requireAnyRole(UserRole.ADMIN, UserRole.SUPER_ADMIN), rejectSubscriptionRequest);
router.delete('/subscribers/:id', authenticate, requireAnyRole(UserRole.ADMIN, UserRole.SUPER_ADMIN), deleteSubscriptionRequest);
export default router;
